#ifndef CRASHREPORTERCONFIG_H
#define CRASHREPORTERCONFIG_H

#define CRASHREPORTER_ORGANIZATION_NAME "@CRASHREPORTER_ORGANIZATION_NAME@"
#define CRASHREPORTER_ORGANIZATION_DOMAIN "@CRASHREPORTER_ORGANIZATION_DOMAIN@"
#define CRASHREPORTER_APPLICATION_NAME "@CRASHREPORTER_APPLICATION_NAME@"
#define CRASHREPORTER_APPLICATION_VERSION "@CRASHREPORTER_APPLICATION_VERSION@"

#define CRASHREPORTER_BUILD_ID "@CMAKE_DATESTAMP_YEAR@@CMAKE_DATESTAMP_MONTH@@CMAKE_DATESTAMP_DAY@000000"

#define CRASHREPORTER_RELEASE_CHANNEL "@CRASHREPORTER_RELEASE_CHANNEL@"

#define CRASHREPORTER_PRODUCT_NAME "@APPLICATION_NAME@"

#define CRASHREPORTER_VERSION_STRING "@VERSION_STRING@"

#define CRASHREPORTER_SUBMIT_URL "@CRASHREPORTER_SUBMIT_URL@"

#endif // CRASHREPORTERCONFIG_H
